Develop
kalonice/training pull request #1
Opened 2017-06-09 17:23 UTC by kalonice

2017-06-11 15:52 UTC, alexey-sidnev requested changes

2017-06-11 15:52 UTC, alexey-sidnev commented on .gitignore
> +build
I believe it's not good idea ignore `build`. Better exclude files by extension: 
 - *.dll
 - *.exe
 - *.o
 - *.so

Remove `build` or add exceptions which we really must exclude.

2017-06-11 15:52 UTC, alexey-sidnev commented on 3rdparty/CMakeLists.txt
> +include_directories(./gtest/googletest/)
Have you tried to build it in Windows? I believe it's not so easy. Take a look on my repository.

2017-06-11 15:52 UTC, alexey-sidnev commented on .travis.yml
> +  - gcc
Which version of gcc will we use? We need C++11 and C++14.

2017-06-11 15:52 UTC, alexey-sidnev commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON)
Looks like CMAKE is really stupid - you repeat requirements twice)

2017-06-11 15:52 UTC, alexey-sidnev commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
You should add `add_compile_options(-Wall -Wpedantic -Wextra -Werror)`. [Link](https://github.com/alexey-sidnev/infrastructure/blob/master/CMakeLists.txt).

2017-06-11 15:52 UTC, alexey-sidnev commented on Makefile
> +	set -e
We don't need Makefile at all.

2017-06-11 21:44 UTC, zingorn commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON)
Done

2017-06-11 21:44 UTC, zingorn commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
Done

2017-06-11 21:44 UTC, zingorn commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
Done

2017-06-11 21:45 UTC, zingorn commented on .travis.yml
> +  - gcc
Done

2017-06-12 07:22 UTC, alexey-sidnev commented on 3rdparty/CMakeLists.txt
> +include_directories(./gtest/googletest/)
Ok, will fix next time.

2017-06-12 07:23 UTC, alexey-sidnev approved these changes

2017-06-12 07:23 UTC, merged